### ISSUE TITLE
How to use PCS and Federated compute platform together?

### ISSUE THREAD

**Issue by ganeshShindeQ** [google/private-compute-services#12]
FCP is an excellent tool for orchestrating Federated Learning (FL), and it also includes client code that can be adapted for various hardware targets. 
How to combine PCS (Private-compute-services) and FCP effectively for federated learning and analytics? could you please share any helpful blogs or resources on this topic?

**Comment by shivanker** [comment]
Please see Google's technical whitepaper on Private Compute Core here - https://arxiv.org/abs/2209.10317
