### ISSUE TITLE
"private compute keeps stopping"

### ISSUE THREAD

**Issue by bdmorin** [google/private-compute-services#14]
This process has taken over my phone in that it interrupts every hour or so that the process has stopped working. It has a out 170mb of background data as well.

What can I do to provide debugging?

**Comment by sandeepwww** [comment]
We have identified some crashes happening recently due to JobScheduler limits on the number of jobs scheduled, and you can expect this to be resolved in few hours.

**Comment by bdmorin** [comment]
Indeed, it seems to have stopped
