### ISSUE TITLE
Is there any ethical way to be employed by Google?

### ISSUE THREAD

**Issue by scanlime** [google/private-compute-services#17]
I know it's common to just throw code out onto GitHub and hope nobody will respond except possibly with vague praise at your openness. I'll offer a different viewpoint: this isn't useful except to make money for Google and further entrench their control over platforms and hardware.

saying hello to https://github.com/RupertBenWiser/Web-Environment-Integrity/issues/28#issuecomment-1651129388 also, it's almost like Google is only here on GitHub for advertising purposes and not to be part of a community of peers.

**Comment by goofy57** [comment]
Please feel free to open a separate issue if you have a technical question on the code published in this repository, or Android's bar for user privacy. We will try our best to help you, there are some publicly available resources on the topic.

Should you have questions about employment at Google (as your issue title suggests), feel free to check https://careers.google.com.

Thanks!

**Comment by scanlime** [comment]
If privacy were really the goal you wouldn't be writing code to harvest user data in a slightly more private way. Is privacy a problem to be solved by writing more code for Google, or by Google doing less? I wouldn't recommend delegating ethics to the recruitment team.

**Comment by bouncinglime** [comment]
I also agree that the initial question was not addressed and that this issue needs to be re-opened.

**Comment by MattEagle95** [comment]
any updates on this?
