### ISSUE TITLE
Broken link in play store description 

### ISSUE THREAD

**Issue by Pansebert** [google/private-compute-services#2]
The link to this repo in the app description is broken (https://github.com/google/private-compute-services.)
Probably because of the dot.

Here is a link to the app store entry https://play.google.com/store/apps/details?id=com.google.android.as.oss

**Comment by desh-woes** [comment]
Hello [Pansebert](https://github.com/Pansebert), 

Thank you for raising this issue. It has been fixed now. 

Kind regards,
